[tool.pytest.ini_options]
filterwarnings = [
    "ignore:numpy.ndarray size changed:RuntimeWarning",
    "ignore:'cgi' is deprecated and slated for removal:DeprecationWarning",
]

[tool.ruff]
line-length = 79
target-version = "py39"

[tool.ruff.lint]
select = [
    "B",  # bugbear
    "E",
    "F",
    "I",
    "T",
]
ignore = [
    "B008",  # do not perform function calls in argument defaults
]

[tool.setuptools_scm]
version_scheme = "post-release"

